// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuWsans87-zKyi_VUCelu_tiBSUJoRznY',
    appId: '1:157444258444:web:c1e4ca811c3fabb4b059a9',
    messagingSenderId: '157444258444',
    projectId: 'fitness-app-7d2d3',
    authDomain: 'fitness-app-7d2d3.firebaseapp.com',
    storageBucket: 'fitness-app-7d2d3.firebasestorage.app',
    measurementId: 'G-EXQZQ18DHM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPUc_HlSqBRyICbXIV7SLuQJ1cqbR2NzI',
    appId: '1:157444258444:android:6157077ff839fa70b059a9',
    messagingSenderId: '157444258444',
    projectId: 'fitness-app-7d2d3',
    storageBucket: 'fitness-app-7d2d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs1OSfT4or4R3-Y-JIhPqQpStAfzUp-nY',
    appId: '1:157444258444:ios:321a829c173f486cb059a9',
    messagingSenderId: '157444258444',
    projectId: 'fitness-app-7d2d3',
    storageBucket: 'fitness-app-7d2d3.firebasestorage.app',
    iosBundleId: 'com.csacademy.fitnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCs1OSfT4or4R3-Y-JIhPqQpStAfzUp-nY',
    appId: '1:157444258444:ios:321a829c173f486cb059a9',
    messagingSenderId: '157444258444',
    projectId: 'fitness-app-7d2d3',
    storageBucket: 'fitness-app-7d2d3.firebasestorage.app',
    iosBundleId: 'com.csacademy.fitnessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuWsans87-zKyi_VUCelu_tiBSUJoRznY',
    appId: '1:157444258444:web:bc064689266691e4b059a9',
    messagingSenderId: '157444258444',
    projectId: 'fitness-app-7d2d3',
    authDomain: 'fitness-app-7d2d3.firebaseapp.com',
    storageBucket: 'fitness-app-7d2d3.firebasestorage.app',
    measurementId: 'G-H151DR1YQX',
  );
}
